# Generated by Django 3.0.3 on 2020-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='name',
            field=models.CharField(default='Music Name', max_length=120),
        ),
    ]
