# Generated by Django 3.0.3 on 2020-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='artist',
            field=models.CharField(default='Michael Bublé', max_length=120),
            preserve_default=False,
        ),
    ]
