# Generated by Django 3.0.3 on 2020-03-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicfile_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('musics', models.ManyToManyField(to='music.MusicFile')),
            ],
        ),
    ]
